#ifndef MESSAGING_H
#define MESSAGING_H

#define MESSAGE_CODE_TEST_CONNECTION 0

#define MESSAGE_CODE_GET_VALUE_FROM_ULTRASONIC_SENSOR 20
#define MESSAGE_CODE_GET_VALUES_FROM_MAGNETOMETER 21
#define MESSAGE_CODE_GET_VALUES_FROM_ACCELEROMETER 22
#define MESSAGE_CODE_GET_VALUES_FROM_GYROSCOPE 23

#define MESSAGE_CODE_GET_BATTERY_VOLTAGE 30
#define MESSAGE_CODE_GET_CHARGER_VOLTAGE 31

#define MESSAGE_CODE_CHANGE_MOTOR_STATE 100

unsigned short messaging_getParametersLength(unsigned char);
void messaging_onMessageRead(unsigned char, unsigned char*, unsigned short);

#endif