//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KennyServer
{
	using System;
	using System.Web;
	using System.Web.UI;

	
	public partial class Default
	{
        protected System.Web.UI.WebControls.Button buttonEnableManualMode;
        protected System.Web.UI.WebControls.Button buttonLeft;
        protected System.Web.UI.WebControls.Button buttonRight;
        protected System.Web.UI.WebControls.Button buttonForward;
        protected System.Web.UI.WebControls.Button buttonBackward;
        protected System.Web.UI.WebControls.Button buttonStartStopConnection;
        protected System.Web.UI.WebControls.Label DateTimeLabel2;

        protected System.Web.UI.WebControls.TextBox textBoxUltrasoniSensor0;
        protected System.Web.UI.WebControls.TextBox textBoxMagnetometerVector;
        protected System.Web.UI.WebControls.TextBox textBoxAccelerometerVector;
        protected System.Web.UI.WebControls.TextBox textBoxGyroscopeVector;
        protected System.Web.UI.WebControls.TextBox textBoxBatteryVoltage;
        protected System.Web.UI.WebControls.TextBox textBoxChargerVoltage;
	}
}

